name: Linting & Tests

on: push

jobs:
  test:
    strategy:
      matrix:
        go-version: ['1.24', '1.25']
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    services:
      chromedp:
        image: docker.io/chromedp/headless-shell:latest
        ports:
          - 9222:9222

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    - name: Disable AppArmor unprivileged userns restriction
      run: echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns
      if: runner.os == 'Linux'

    - name: Set up tools
      env:
        PISCES_CHROMEDP_REMOTE_URL: "http://localhost:9222"
      run: |
        go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

    - name: Run linting
      uses: golangci/golangci-lint-action@v9
      with:
        version: v2.6

    - name: Run tests
      run: go test ./...
